device: "cuda"
seed: 1337
eval_only: false

# Training configuration
batch_size: 256
epochs_ssl_init: 10
epochs_finetune: 10

use_lamb: true
betas:
- 0.9
- 0.999
eps: 1.0e-6
lr_ssl_init: 2.516152722130999e-3
wd_ssl_init: 1.2775200014634934e-4
warmup_pct_init: 0.1
min_lr_factor: 0.01
lr_finetune: 5.70373305632515e-4
wd_finetune: 1.5399401149371588e-3
warmup_pct_ft: 0.1
min_lr_factor: 0.01

shrink_p_ft: 1.0
shrink_loc_ft: 0.1
shrink_speed_ft: 10.0

grad_clip_norm: 1.0

ssl_weight: 1.0
sl_weight: 1.0

# Test-time calibration configuration
ttc_batch_size: 64
buffer_sizes:
  unlabeled: 64
  labeled: 8
sampling_ratio: 0.25

n_update_per_batch: 5
ttc_lr: 1.0e-3
ttc_momentum: 0.9
ttc_weight_decay: 1.0e-3

shrink_p_ttc: 2.5
shrink_loc_ttc: 0.0
shrink_speed_ttc: 10.0

ssl_weight_ttc: 1.0
sl_weight_ttc: 1.0

# Model configuration
patch_size: 30
patch_stride: 15
input_channels: 1
embed_dim: 512
num_heads: 8
depth: 4
ckpt_path: null

# Replace with local paths before real runs.
savedir: "./outputs/calib_based/ttc"
index_data_path: "./data/pulsedb/index"
waveform_data_path: "./data/pulsedb/waveform"
train_index_filename: "train.parquet"
valid_index_filename: "valid.parquet"
test_index_filename: "test.parquet"

# Replace with your own column names before real runs.
cal_column: "calib_point"
case_id_column: 'caseid'
segment_id_column: 'seg_num'
sig_filename_column: 'filepath'
sbp_column: 'sbp'
dbp_column: 'dbp'

# PPG Preprocessing
crop_second: 10
fs: 125
resample_fs: 125
transform:
  - name: Resample
    params:
      target_length: ${crop_second} * ${resample_fs}
  - name: ButterworthFilter
    params:
      fs: ${resample_fs}
      cutoff: [0.8, 8]
      order: 2
      btype: bandpass
  - name: Standardize
    params:
      axis: -1
  - name: ToTensor
