GPU: 0
seed: 419
eval_only: false

# Training configuration
use_amp: true
n_epochs: 100
num_iters: 2000
batch_size: 32
optimizer: "adam"
warmup_updates: 5000
weight_decay: 0.01
learning_rate: 0.0001
skip_val: -1

# Model configuration
model_name: 'PPG2BPNet'
latent_dim: 128
dropout: 0.22
se_ratio: 0.25

# Set to empty to train from scratch.
reload_path: ""
reload_optimizer: false

# Replace with local paths before real runs.
exp_name: 'calib_based'
exp_trial_name: 'ppg2bpnet'
dump_path: './outputs'
index_data_path: './data/pulsedb/index'
waveform_data_path: './data/pulsedb/waveform'
train_index_filename: 'train.parquet'
valid_index_filename: 'valid.parquet'
test_index_filename: 'test.parquet'

# Replace with your own column names before real runs.
cal_column: 'calib_point'
case_id_column: 'caseid'
segment_id_column: 'seg_num'
sig_filename_column: 'filepath'
sbp_column: 'sbp'
dbp_column: 'dbp'

# Dataloader
num_workers: 32

# PPG Preprocessing
crop_second: 10
fs: 125
resample_fs: 125
transform:
  - name: Resample
    params:
      target_length: ${crop_second} * ${resample_fs}
  - name: ButterworthFilter
    params:
      fs: ${resample_fs}
      cutoff: [0.8, 8]
      order: 2
      btype: bandpass
  - name: Standardize
    params:
      axis: -1
  - name: ToTensor
